name: Production Build and Deploy
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'
env:
  URL: prod.oleksii.org

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://${{ env.URL }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
      - name: Checkout Prod Target
        uses: actions/checkout@v2
        with:
          repository: 0leksii/prod-site-deploy
          path: 'deploy'
          token: ${{ secrets.PAT }}

      - name: Push files to target
        run: |
          rsync ./build ./deploy --exclude .github
          cd deploy
          echo ${{ env.URL }} > CNAME
          git add .
          git commit -m $GITHUB_SHA
          git push